[build]
  base = "frontend"
  publish = "dist"
  command = "npm install && npm run build"

  [[redirects]]
  from = "/api/*"
  to = "http://localhost:8080/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/uploads/*"
  to = "http://localhost:8080/uploads/:splat"
  status = 200
  force = true