[build]
  base = "frontend"
  publish = "dist"
  command = "npm install && npm run build"

 [[redirects]]
from = "/api/*"
to = "https://social-web-axbp.onrender.com/:splat"
status = 200
force = true

[[redirects]]
from = "/uploads/*"
to = "https://social-web-axbp.onrender.com/uploads/:splat"
status = 200
force = true
